[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
solc_version = '0.8.24'
evm_version = 'cancun'
viaIR = true
optimizer = true
optimizer_runs = 200

[profile.ci]
verbosity = 5
fuzz_runs = 10000

[rpc_endpoints]
sepolia = "${SEPOLIA_RPC_URL}"
mainnet = "${MAINNET_RPC_URL}"
arbitrum = "${ARBITRUM_RPC_URL}"
optimism = "${OPTIMISM_RPC_URL}"
avalanche = "${AVALANCHE_RPC_URL}"
polygon = "${POLYGON_RPC_URL}"
bera_bartio = "${BERA_BARTIO_RPC_URL}"

[etherscan]
sepolia = { key = "${ETHERSCAN_API_KEY}", url = "https://api-sepolia.etherscan.io/api" }
mainnet = { key = "${ETHERSCAN_API_KEY}" }
arbitrum = { key = "${ARBISCAN_API_KEY}", url = "https://api.arbiscan.io/api" }
optimism = { key = "${OPTIMISM_API_KEY}", url = "https://api-optimistic.etherscan.io/api" }
avalanche = { key = "${SNOWTRACE_API_KEY}", url = "https://api.snowtrace.io/api" }
polygon = { key = "${POLYGONSCAN_API_KEY}", url = "https://api.polygonscan.com/api" }