[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
solc_version = '0.8.24'
evm_version = 'cancun'
viaIR = true
optimizer = true
optimizer_runs = 200
ffi = true
fs_permissions = [{ access = "read-write", path = "./deployments" }, { access = "read-write", path = ".forge-snapshots/"}]

[profile.ci]
verbosity = 5
fuzz_runs = 10000

[rpc_endpoints]
sepolia = "${RPC_URL_SEPOLIA}"
mainnet = "${RPC_URL_MAINNET}"
base = "${RPC_URL_BASE}"
arbitrum = "${RPC_URL_ARBITRUM}"

[etherscan]
sepolia = { key = "${ETHERSCAN_API_KEY}" }
mainnet = { key = "${ETHERSCAN_API_KEY}" }
base = { key = "${BASESCAN_API_KEY}", url = "https://api.basescan.org/api" }
arbitrum = { key = "${ETHERSCAN_API_KEY_ARBITRUM}" }